fe/.prettierrc.json, fe/src/components/style/theme.ts
-[] 기능 추가
-[] 기능 삭제
-[] 코드 리팩토링
-[] 버그 수정
-[o] 의존성, 환경 변수, 빌드 관련 코드 업데이트
prettier 설정 변경
=> Setting: prettier 변경

be/cocktail/src/main/java/com/BE/cocktail/customBookmark/CustomBookmark.java, be/cocktail/src/main/java/com/BE/cocktail/customRecipe/CustomRecipe.java
-[O] 기능 추가
-[] 기능 삭제
-[] 코드 리팩토링
-[] 버그 수정
- CustomBookmark/Recipe의 Entity 구현함
- 각 팀원들의 담당 파트에 Entity를 미리 구현해서 환경세팅 진행
CustomBookmark / Recipe 의 Entity 클래스가 있어야함
=> Feat : CustomBookmark/Recipe Entity 구현

be/cocktail/src/main/java/com/BE/cocktail/regularRecipe/RegularRecipeController.java, be/cocktail/src/main/java/com/BE/cocktail/regularRecipe/RegularRecipeRepository.java, be/cocktail/src/main/java/com/BE/cocktail/regularRecipe/RegularRecipeService.java
-[O] 기능 추가
-[ ] 기능 삭제
-[ ] 코드 리팩토링
-[ ] 버그 수정
- RegularRecipeController/Service/Repository 환경 구성 
controller/Service/Repository 클래스들이 있어야함
=> Feat : RegularRecipe Api 작업환경 구성

be/cocktail/src/main/resources/application.yml
-[O] 기능 추가
-[ ] 기능 삭제
-[ ] 코드 리팩토링
-[ ] 버그 수정
- yml에 mySql 연결 코드 작성
- mySql이 연결 되어야함
=> Feat : mySql 환경 세팅

be/cocktail/src/main/java/com/BE/cocktail/customRecipe/CustomRecipeController.java, be/cocktail/src/main/java/com/BE/cocktail/customRecipe/CustomRecipeRepository.java, be/cocktail/src/main/java/com/BE/cocktail/customRecipe/CustomRecipeService.java
-[O] 기능 추가
-[ ] 기능 삭제
-[ ] 코드 리팩토링
-[ ] 버그 수정
- CustomRecipeController/Service/Repository 환경 구성
- CustomRecipeController/service/Repository 클래스들이 존재해야함
=> Feat : CustomRecipe API 환경구성

be/cocktail/src/main/resources/application.yml
-[ ] 기능 추가
-[O] 기능 삭제
-[ ] 코드 리팩토링
-[ ] 버그 수정
- 비번 삭제
- 비번 삭제되어야함
=> mysql 비번 삭제

be/cocktail/build.gradle, be/cocktail/src/main/java/com/BE/cocktail/customRecipe/CustomRecipe.java, be/cocktail/src/main/java/com/BE/cocktail/customRecipe/CustomRecipeController.java, be/cocktail/src/main/java/com/BE/cocktail/customRecipe/CustomRecipeService.java, be/cocktail/src/main/java/com/BE/cocktail/customRecipe/dto/CustomRecipePostDto.java, be/cocktail/src/main/java/com/BE/cocktail/customRecipe/dto/CustomRecipeResponseDto.java, be/cocktail/src/main/java/com/BE/cocktail/customRecipe/dto/CustomRecipeResponseDtoList.java, be/cocktail/src/main/java/com/BE/cocktail/ingredient/Ingredient.java, be/cocktail/src/main/java/com/BE/cocktail/member/Member.java, be/cocktail/src/main/java/com/BE/cocktail/regularRecipe/RegularRecipe.java, be/cocktail/src/main/resources/application.yml
-[O] 기능 추가
-[ ] 기능 삭제
-[ ] 코드 리팩토링
-[ ] 버그 수정
=> Feat : customRecipe submit,findAll 구현

be/cocktail/src/main/java/com/BE/cocktail/apiResponse/ApiResponse.java, be/cocktail/src/main/java/com/BE/cocktail/apiResponse/CocktailRtnConsts.java, be/cocktail/src/main/java/com/BE/cocktail/apiResponse/CocktailRtnGrp.java
-[O] 기능 추가
-[ ] 기능 삭제
-[ ] 코드 리팩토링
-[ ] 버그 수정
- 응답을 좀 더 세분화하여 관리하기 위해서 ResponseEntity대신 ApiResponse를 구현함
- 응답시 ApiResponse에서 설정한 대로 응답바디가 나와야함
=> Feat : ApiResponse 구현

be/cocktail/src/main/java/com/BE/cocktail/ingredient/IngredientResponses.java, be/cocktail/src/main/java/com/BE/cocktail/regularRecipe/RegularRecipe.java, be/cocktail/src/main/java/com/BE/cocktail/regularRecipe/RegularRecipeController.java, be/cocktail/src/main/java/com/BE/cocktail/regularRecipe/RegularRecipeRepository.java, be/cocktail/src/main/java/com/BE/cocktail/regularRecipe/RegularRecipeService.java, be/cocktail/src/main/java/com/BE/cocktail/regularRecipe/dto/RegularRecipeCreateDto.java, be/cocktail/src/main/java/com/BE/cocktail/regularRecipe/dto/RegularRecipeCreateResponseDto.java, be/cocktail/src/main/java/com/BE/cocktail/regularRecipe/dto/RegularRecipeSingleResponseDto.java, be/cocktail/src/main/java/com/BE/cocktail/regularRecipe/dto/SingleResponse.java
-[O] 기능 추가
-[ ] 기능 삭제
-[ ] 코드 리팩토링
-[ ] 버그 수정
- 정규레시피 상세조회 하는 API 구현
- 정규레피시 상세조회가 가능해야한다
=> Feat : 정규레시피 상세조회 API 구현

be/cocktail/src/main/java/com/BE/cocktail/exception/CocktailException.java, be/cocktail/src/main/java/com/BE/cocktail/exception/GlobalExceptionHandler.java
-[O] 기능 추가
-[ ] 기능 삭제
-[ ] 코드 리팩토링
-[ ] 버그 수정
- exception handler 구현
- CocktailException이 발생할때 exception handler가 캐치해야함
=> Feat : Exception Handler 구현

be/cocktail/src/main/java/com/BE/cocktail/auth/SecurityConfig.java
-[O] 기능 추가
-[ ] 기능 삭제
-[ ] 코드 리팩토링
-[ ] 버그 수정
- securityConfig를 구현하여 모든 포트 허용함
- postman으로 요청이 들어가야함
=> Feat : securityConfig 구현

be/cocktail/src/main/java/com/BE/cocktail/customRecipe/CustomRecipe.java, be/cocktail/src/main/java/com/BE/cocktail/ingredient/Ingredient.java, be/cocktail/src/main/java/com/BE/cocktail/regularRecipe/RegularRecipe.java
-[O] 기능 추가
-[ ] 기능 삭제
-[ ] 코드 리팩토링
-[ ] 버그 수정
- 데이터가 삭제되었는지를 확인하기 위해서 boolean 타입인 status컬럼을 추가하여 관리하도록함
- 데이터 조회시 데이터베이스에 status컬럼이 확인해야함
=> Feat : 회원레시피, 정규레시피, 재료에 status 컬럼추가

be/cocktail/src/main/java/com/BE/cocktail/regularRecipe/RegularRecipeController.java, be/cocktail/src/main/java/com/BE/cocktail/regularRecipe/RegularRecipeRepository.java, be/cocktail/src/main/java/com/BE/cocktail/regularRecipe/RegularRecipeService.java, be/cocktail/src/main/java/com/BE/cocktail/regularRecipe/dto/MultiResponse.java, be/cocktail/src/main/java/com/BE/cocktail/regularRecipe/dto/RegularRecipeMultiResponseDto.java
-[0] 기능 추가
-[] 기능 삭제
-[0] 코드 리팩토링
-[] 버그 수정
알코올 도수에 맞게 그룹으로 응답 처리
=> Feat : Regular 전체 레시피 조회 구현

be/cocktail/src/main/java/com/BE/cocktail/regularRecipe/RegularRecipeService.java
-[ ] 기능 추가
-[ ] 기능 삭제
-[O] 코드 리팩토링
-[ ] 버그 수정
- regularRecipe List를 저장할시 repository.saveAll로 저장하는 것으로 변경
- 데이터베이스에 regularRecipe들이 저장되어야함
=> Refactor : RegularRecipe DB 저장 코드 변경

fe/src/pages/CocktailRegistration.tsx, fe/src/pages/LoginPage.tsx
-[o] 기능 추가
-[x] 기능 삭제
-[x] 코드 리팩토링
-[x] 버그 수정
-[x] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- 레시피등록페이지 재료입력 폼 추가 및 삭제기능 추가
- 하단 Plus 버튼을 누르면 재료입력폼이  아래로 추가됨
- 입력폼에 hover했을 시 Delete버튼 활성화. 클릭시 삭제.
=> feat: 레시피등록페이지 재료입력폼 추가 및 삭제기능

be/cocktail/src/main/java/com/BE/cocktail/apiResponse/CocktailRtnConsts.java, be/cocktail/src/main/java/com/BE/cocktail/customRecipe/CustomRecipeController.java, be/cocktail/src/main/java/com/BE/cocktail/customRecipe/CustomRecipeService.java
-[O] 기능 추가
-[ ] 기능 삭제
-[] 코드 리팩토링
-[ ] 버그 수정
1.  CuntomRecipeController에 ApiResponse로 형변환
2.  CuntomRecipe 삭제 응답메세지추가
1. 응답바디 ApiResponse 형태로 바뀜
2. 삭제시 성공메세지와 중복삭제할시 에러메세지 나옴
=> Feat : CuntomRecipe 삭제 응답메세지추가, CuntomRecipeController에 ApiResponse로 형변환

fe/data.json, fe/src/components/card/CardList.tsx, fe/src/components/card/SearchResultsTab.tsx, fe/src/components/card/SearchedRecipe.tsx, fe/src/pages/CustomRecipes.tsx, fe/src/pages/Main.tsx, fe/src/pages/SearchResults.tsx, fe/src/utils/query.ts
-[o] 기능 추가
-[ ] 기능 삭제
-[o] 코드 리팩토링
-[ ] 버그 수정
- 레시피 카드 get 요청 => 기존 레시피 카드와 검색 카드 요청으로 분리
- api 변경으로 인한 cardlist 컴포넌트 refactoring
- api 변경으로 인한 페이지 레이아웃 변경
- 기존 화면과 동일
- 검색 결과 화면 => tab 형식의 정규, 커스텀 레시피 분류로 변경
=> Refactor : api 변경에 따른 코드 수정

be/cocktail/src/main/java/com/BE/cocktail/dto/regularRecipe/MultiResponse.java, be/cocktail/src/main/java/com/BE/cocktail/persistence/repository/customRecipe/CustomRecipeRepository.java, be/cocktail/src/main/java/com/BE/cocktail/service/customRecipe/CustomRecipeService.java
-[O] 오타 수정
-[ ] 기능 추가
-[ ] 기능 삭제
-[ ] 코드 리팩토링
-[ ] 버그 수정
- findbyKeyword -> findByKeyword로 변경
- customRepository에서 findByKeyword로 메서드명이 바뀌어 있어야함
=> Style : findbyKeyword 메서드명 오타수정

be/cocktail/src/main/java/com/BE/cocktail/controller/regularRecipe/RegularRecipeController.java, be/cocktail/src/main/java/com/BE/cocktail/dto/regularRecipe/RegularRecipeResponse.java, be/cocktail/src/main/java/com/BE/cocktail/persistence/repository/regularRecipe/RegularRecipeRepository.java, be/cocktail/src/main/java/com/BE/cocktail/service/regularRecipe/RegularRecipeService.java
-[0] 기능 추가
-[] 기능 삭제
-[0] 코드 리팩토링
-[] 버그 수정
정규 레시피 페이지네이션 기능 추가 및 클래스 명, 메서드 명 변경
도수 0 =  0 레시피
도수 1 = 1 ~ 9 레시피
도수 10 = 10 ~ 19 레시피
도수 20 = 20 ~ 29 레시피
도수 30 = 30 ~ 39 레시피
도수 40 = 40 이상인 레시피
=> Feat : 정규 레시피 도수별 전체 조회

be/cocktail/src/main/java/com/BE/cocktail/controller/customeRecipe/CustomRecipeController.java, be/cocktail/src/main/java/com/BE/cocktail/dto/customRecipe/CustomRecipeGetResponseDto.java, be/cocktail/src/main/java/com/BE/cocktail/service/customRecipe/CustomRecipeService.java
-[0] 기능 추가
-[] 기능 삭제
-[] 코드 리팩토링
-[] 버그 수정
커스텀 레시피 상세 조회 구현
커스텀 레시피 상세 조회시 상세 조회 데이터 전송
=> Feat : 커스텀 레시피 상세 조회

be/cocktail/src/main/java/com/BE/cocktail/dto/apiResponse/CocktailRtnConsts.java
-[0] 기능 추가
-[] 기능 삭제
-[] 코드 리팩토링
-[] 버그 수정
칵테일 레시피 에러메세지 작성
칵테일 레시피 에러메세지 응답
=> Feat : 칵테일 레시피 에러메세지

fe/src/App.tsx, fe/src/components/myPage/MenuBar.tsx, fe/src/components/myPage/MyInfo.tsx, fe/src/pages/Mypage.tsx
-[O] 기능 추가
-[ ] 기능 삭제
-[ ] 코드 리팩토링
-[ ] 버그 수정
- Mypage를 구성하는 ManuBar 컴포넌트와 MyInfo컴포넌트 레이아웃 생성
- Mypage 레이아웃 생성
=> Feat: Mypage 레이아웃 잡기

fe/src/App.tsx, fe/src/components/header/Header.tsx, fe/src/components/loginbutton/GoogleSignIn.tsx, fe/src/pages/SignIn.tsx, fe/src/pages/SignUp.tsx
-[o] 기능 추가
-[ ] 기능 삭제
-[o] 코드 리팩토링
-[ ] 버그 수정
- 회원가입페이지 복구
- 로그인페이지에서 회원가입으로 이동할 수 있는 Link추가
- 회원가입페이지 복구로 인한 path경로 수정
- 로그인 페이지의 입력폼 하단에 회원가입으로 이동 가능
- 나머지 회원가입페이지에 대한 path경로 문제없음
=> Feat: 회원가입페이지복구- Design: 회원가입Link 추가 및 path경로수정

fe/data.json, fe/src/components/card/SearchResultsTab.tsx, fe/src/components/card/SearchedRecipe.tsx, fe/src/pages/SearchResults.tsx, fe/src/utils/query.ts
-[] 기능 추가
-[ ] 기능 삭제
-[o] 코드 리팩토링
-[ ] 버그 수정
- axios에 defaults baseURL 추가
- SearchResultsTab 내의 props 타입명 변경
- 기존 기능 유지
=> Refactor : type 이름 변경 및 axios baseURL 추가 

be/cocktail/build.gradle, be/cocktail/src/main/java/com/BE/cocktail/auth/CustomAuthorityUtils.java, be/cocktail/src/main/java/com/BE/cocktail/auth/MemberDetailsService.java, be/cocktail/src/main/java/com/BE/cocktail/auth/SecurityConfig.java, be/cocktail/src/main/java/com/BE/cocktail/auth/jwt/JwtAuthenticationFilter.java, be/cocktail/src/main/java/com/BE/cocktail/auth/jwt/JwtTokenizer.java, be/cocktail/src/main/java/com/BE/cocktail/auth/jwt/JwtVerificationFilter.java, be/cocktail/src/main/java/com/BE/cocktail/controller/member/MemberController.java, be/cocktail/src/main/java/com/BE/cocktail/dto/LoginDto.java, be/cocktail/src/main/java/com/BE/cocktail/dto/apiResponse/ApiResponse.java, be/cocktail/src/main/java/com/BE/cocktail/dto/member/SignUpDto.java, be/cocktail/src/main/java/com/BE/cocktail/dto/regularRecipe/RegularRecipeMultiResponseDto.java, be/cocktail/src/main/java/com/BE/cocktail/persistence/domain/customRecipe/CustomRecipe.java, be/cocktail/src/main/java/com/BE/cocktail/persistence/domain/member/Member.java, be/cocktail/src/main/java/com/BE/cocktail/persistence/repository/member/MemberRepository.java, be/cocktail/src/main/java/com/BE/cocktail/service/customRecipe/CustomRecipeService.java, be/cocktail/src/main/java/com/BE/cocktail/service/member/MemberService.java, be/cocktail/src/main/java/com/BE/cocktail/utils/GetAuthUserUtils.java, be/cocktail/src/main/resources/application.yml
-[O] 기능 추가
-[ ] 기능 삭제
-[ ] 코드 리팩토링
-[ ] 버그 수정
- Jwt token 인증 방식 구현
- 로그인시 응답값으로 JWT 토큰이 전달 되어야함, 커스텀게시글을 만드는 요청을 보낼때 로그인한 사용자가 아니면 게시글 작성이 안되어야 한다
=> Feat : Jwt 설정

fe/src/components/loginbutton/GoogleSignIn.tsx, fe/src/pages/DetailPage.tsx, fe/src/pages/SignIn.tsx, fe/src/pages/SignUp.tsx
-[O] 기능 추가
-[ ] 기능 삭제
-[ ] 코드 리팩토링
-[ ] 버그 수정
- 로고 클릭시 메인페이지로 이동하는 기능 추가
- 기존 기능 유지
=> Feat: Logo Link기능 추가

be/cocktail/src/main/java/com/BE/cocktail/dto/customRecipe/CustomRecipeResponseDto.java
-[] 기능 추가
-[] 기능 삭제
-[0] 코드 리팩토링
-[] 버그 수정
커스텀 전체 레시피 응답에 id, description 추가
id와 description 정상 응답
=> Refactor : 커스텀 전체 레시피 응답에 id와 description 추가

be/cocktail/src/main/java/com/BE/cocktail/dto/regularRecipe/RegularRecipeResponse.java, be/cocktail/src/main/java/com/BE/cocktail/persistence/domain/regularRecipe/RegularRecipe.java
-[] 기능 추가
-[] 기능 삭제
-[0] 코드 리팩토링
-[] 버그 수정
전체 전체 레시피 응답에 id와 description 추가
id, description 응답 정상
=> Refactor : 전체 전체 레시피 응답에 id와 description 추가

fe/package-lock.json, fe/package.json, fe/src/pages/CocktailRegistration.tsx
-[ ] 기능 추가
-[ ] 기능 삭제
-[o] 코드 리팩토링
-[ ] 버그 수정
- api요청 POST방식 react-query useMutation적용 및 api연결
- 재료선택 폼 초기값 수정
- useMutation을 통해서 이전의 코드와 동일하게 ec2서버로 데이터 전송이 정상적으로 됨
- Form데이터는 구현에 문제가 있어 추후 도입예정
=> Refactor: api서버요청방식react-query적용 및 초기값설정변경- Design: 디자인변경

fe/src/components/imageupload/ImageUpload.tsx, fe/src/pages/CocktailRegistration.tsx
-[ ] 기능 추가
-[ ] 기능 삭제
-[o] 코드 리팩토링
-[ ] 버그 수정
- 커스텀레시피등록 페이지 이미지 업로드기능 컴포넌트화
- 레시피등록 페이지의 이미지업로드기능을 마이페이지 프로필사진에서 사용가능
=> Refactor: 이미지업로드폼 컴포넌트분리

fe/package.json, fe/src/components/card/Card.tsx, fe/src/components/card/CardList.tsx, fe/src/components/card/RecipePagination.tsx, fe/src/components/card/SearchedRecipe.tsx, fe/src/pages/CustomRecipes.tsx, fe/src/pages/DetailPage.tsx, fe/src/pages/Main.tsx, fe/src/pages/SearchResults.tsx, fe/src/utils/query.ts
-[ ] 기능 추가
-[ ] 기능 삭제
-[o] 코드 리팩토링
-[ ] 버그 수정
- 전반적인 get 요청 타입과 엔드 포인트 변경
- proxy 추가
- recipe card type 수정
- 로딩 gif 추가
- recipe 데이터가 존재하지 않는 경우 안내 문자 등장 (수정 예정)
- 레시피 도수별 pagination 컴포넌트 분리
- 검색 결과 페이지 pagination 추가
- 기존 기능 유지
- 요청 완료 전까지 loading gif 등장
- 요청이 성공했지만 데이터가 없는 경우 레시피가 존재하지 않는다는 메세지 등장
=> Refactor : 레시피 목록 조회 백엔드 api 적용

fe/src/components/myPage/EditMyInfo.tsx, fe/src/components/myPage/MyInfo.tsx, fe/src/pages/Mypage.tsx
-[O] 기능 추가
-[ ] 기능 삭제
-[O] 코드 리팩토링
-[ ] 버그 수정
- 기존의 MyInfo 컴포넌트를 EditMyInfo컴포넌트로 파일명 변경
- MyInfo 컴포넌트 새로 생성 및 react-query 적용
- 내 정보를 볼 수 있는 컴포넌트와 내 정보를 수정하는 컴포넌트 분리
=> Feat: MyInfo컴포넌트 레이아웃 변경 및 react-query적용

fe/src/components/myPage/EditMyInfo.tsx
-[ ] 기능 추가
-[ ] 기능 삭제
-[O] 코드 리팩토링
-[ ] 버그 수정
- EditMyInfo 컴포넌트 fetch 부분 axios로 교체
- 현재 기능 유지
=> Refactor: EditMyInfo 컴포넌트 axios적용

be/cocktail/src/main/java/com/BE/cocktail/controller/customeRecipe/CustomRecipeController.java, be/cocktail/src/main/java/com/BE/cocktail/controller/member/MemberController.java, be/cocktail/src/main/java/com/BE/cocktail/dto/LoginDto.java, be/cocktail/src/main/java/com/BE/cocktail/dto/customRecipe/CustomPatchDto.java, be/cocktail/src/main/java/com/BE/cocktail/dto/customRecipe/CustomRecipePostDto.java, be/cocktail/src/main/java/com/BE/cocktail/dto/member/SignUpDto.java, be/cocktail/src/main/java/com/BE/cocktail/service/customRecipe/CustomRecipeService.java
-[O] 기능 추가
-[ ] 기능 삭제
-[ ] 코드 리팩토링
-[ ] 버그 수정
CustomRecipe 등록,수정 & 회원가입시 유효성 검사 기능 추가
CustomRecipe 등록, CustomRecipe 수정, 회원가입시 유효성 검사를 진행
1. CustomRecipe name : 한글만 사용 가능 / 1자~ 약 85자
2. CustomRecipe description : 한글,알파벳 사용 가능, 특수문자 사용불가/ 1자~약 85자
3. CustomRecipe recipe : 문자 제한 없음 / 최대 약 300자
4. CustomRecipe ingredient : 한글,숫자,알파벳 사용가능, 특수문자 사용불가
5. 회원가입 nickname : 한글, 영문, 숫자, 특수문자 (- _ .) 사용가능 / 2 ~ 12자
6. 회원가입 email : 이메일 형식
7. 회원가입 password : 영어,숫자,특수문자 사용, 영어&특수문자 필수포함 / 6자~24자
=> Feat : 유효성 검사 기능 추가

be/cocktail/build.gradle, be/cocktail/src/main/java/com/BE/cocktail/controller/customeRecipe/CustomRecipeController.java, be/cocktail/src/main/java/com/BE/cocktail/controller/member/MemberController.java, be/cocktail/src/main/java/com/BE/cocktail/controller/regularRecipe/RegularRecipeController.java, be/cocktail/src/main/java/com/BE/cocktail/dto/customRecipe/CustomRecipeGetResponseDto.java, be/cocktail/src/main/java/com/BE/cocktail/dto/regularRecipe/RegularRecipeGetResponseDto.java, be/cocktail/src/main/java/com/BE/cocktail/persistence/domain/bookmark/Bookmark.java, be/cocktail/src/main/java/com/BE/cocktail/swagger/SwaggerConfig.java, be/cocktail/src/main/resources/application.yml
-[0] 기능 추가
-[] 기능 삭제
-[] 코드 리팩토링
-[] 버그 수정
swagger 적용 및 북마크 엔티티 작성
swagger 적용 및 북마크 엔티티 작성 성공
=> Feat : Swagger 및 북마크 엔티티 작성

be/cocktail/src/main/java/com/BE/cocktail/auth/SecurityConfig.java, be/cocktail/src/main/java/com/BE/cocktail/dto/customRecipe/CustomRecipeGetResponseDto.java, be/cocktail/src/main/java/com/BE/cocktail/dto/customRecipe/CustomSearchResponseDto.java, be/cocktail/src/main/java/com/BE/cocktail/dto/regularRecipe/RegularRecipeGetResponseDto.java, be/cocktail/src/main/java/com/BE/cocktail/dto/regularRecipe/RegularSearchResponseDto.java
-[O] 기능 추가
-[] 기능 삭제
-[] 코드 리팩토링
-[] 버그 수정
- 레시피 관련 응답에 레시피 Id추가
- 레시피 응답에 레시피 Id가 있어야함
=> Feat : 응답에 레시피 Id 추가

be/cocktail/src/main/java/com/BE/cocktail/service/regularRecipe/RegularRecipeService.java
-[] 기능 추가
-[] 기능 삭제
-[0] 코드 리팩토링
-[] 버그 수정
알코올 도수 범위 30이상으로 변경
알코올 도수 범위 30이상으로 변경함
0 -> 0 
1 -> 1 ~ 9
10 -> 10 ~ 19
20 -> 20 ~ 29
30 -> 30 이상
=> Refactor : 알코올 도수 범위 30이상으로 변경

be/cocktail/build.gradle, be/cocktail/src/main/java/com/BE/cocktail/dto/apiResponse/CocktailRtnConsts.java, be/cocktail/src/main/java/com/BE/cocktail/persistence/domain/member/Member.java, be/cocktail/src/main/java/com/BE/cocktail/persistence/domain/member/MemberPrincipal.java, be/cocktail/src/main/java/com/BE/cocktail/persistence/domain/member/Role.java, be/cocktail/src/main/java/com/BE/cocktail/security/jwt1/JwtTokenProvider.java, be/cocktail/src/main/java/com/BE/cocktail/security/jwt1/filter/JwtAuthenticationFilter.java, be/cocktail/src/main/java/com/BE/cocktail/security/jwt1/filter/JwtVerificationFilter.java, be/cocktail/src/main/java/com/BE/cocktail/security/jwt1/handler/MemberAuthenticationFailureHandler.java, be/cocktail/src/main/java/com/BE/cocktail/security/jwt1/handler/MemberAuthenticationSuccessHandler.java, be/cocktail/src/main/java/com/BE/cocktail/security/oauth/CustomOAuth2Member.java, be/cocktail/src/main/java/com/BE/cocktail/security/oauth/OAuthAttributes.java, be/cocktail/src/main/java/com/BE/cocktail/security/oauth/handler/OAuth2LoginFailureHandler.java, be/cocktail/src/main/java/com/BE/cocktail/security/oauth/handler/OAuth2LoginSuccessHandler.java, be/cocktail/src/main/java/com/BE/cocktail/security/oauth/service/CustomOAuth2MemberService.java, be/cocktail/src/main/java/com/BE/cocktail/security/oauth/userinfo/GoogleMemberInfo.java, be/cocktail/src/main/java/com/BE/cocktail/security/oauth/userinfo/OAuth2MemberInfo.java, be/cocktail/src/main/java/com/BE/cocktail/security/oauth/userinfo/ProviderType.java, be/cocktail/src/main/java/com/BE/cocktail/service/member/MemberService.java, be/cocktail/src/main/java/com/BE/cocktail/service/member/PrincipalDetailsService.java, be/cocktail/src/main/java/com/BE/cocktail/utils/AuthorityUtils.java, be/cocktail/src/main/resources/application.yml
-[0] 기능 추가
-[] 기능 삭제
-[] 코드 리팩토링
-[] 버그 수정
OAuth2 구글 적용
OAuth2 구글 적용 정상 로그인
=> Feat : OAuth2 구글 적용

fe/src/pages/CocktailRegistration.tsx, fe/src/pages/SignUp.tsx
-[o] 기능 추가
-[ ] 기능 삭제
-[o] 코드 리팩토링
-[ ] 버그 수정
- POST요청 함수 이름 변경 및 서버api연결
- 서버 API로 회원정보 데이터 정상적으로 전송 확인
=> Refactor: SignUp페이지 서버api 데이터 연결 및 fetch함수명 변경

be/cocktail/src/main/java/com/BE/cocktail/dto/LoginResponseDto.java, be/cocktail/src/main/java/com/BE/cocktail/security/config/SecurityConfig.java
-[0] 기능 추가
-[] 기능 삭제
-[] 코드 리팩토링
-[] 버그 수정
Config, dto 추가
Config, dto 추가
=> Feat : Config, dto 추가

fe/src/pages/DetailPage.tsx
-[ ] 기능 추가
-[ ] 기능 삭제
-[o] 코드 리팩토링
-[ ] 버그 수정
- DetailPage 칵테일 이미지 크기 표준화
- DetailPage 정보 폼 Container 디자인수정
- 모든 칵테일 이미지가 설정한 크기만큼 렌더링됨
=> Design: DetailPage 디자인수정

fe/src/components/NavBar/NavBar.tsx, fe/src/components/card/Card.tsx, fe/src/components/card/CardList.tsx, fe/src/components/card/LoadingComponent.tsx, fe/src/components/header/Header.tsx, fe/src/components/myPage/MenuBar.tsx, fe/src/pages/CocktailRegistration.tsx, fe/src/pages/CustomRecipes.tsx, fe/src/pages/Mypage.tsx, fe/src/utils/tokeninstance.ts
-[o] 기능 추가
-[ ] 기능 삭제
-[o] 코드 리팩토링
-[ ] 버그 수정
- MyPage MenuBar 버튼 기능 추가
- Header navBar z-index 수정
- 마이 페이지의 메뉴 버튼을 누르면 그에 해당하는 컨텐츠가 나타남
=> Feat : MyPage 버튼 기능 추가

fe/src/components/myPage/MyInfo.tsx, fe/src/hooks/useFetchRecipe.tsx, fe/src/pages/CocktailEdit.tsx, fe/src/pages/DetailPage.tsx, fe/src/pages/Mypage.tsx
-[ ] 기능 추가
-[ ] 기능 삭제
-[o] 코드 리팩토링
-[ ] 버그 수정
- 커스텀레시피와 정규레시피의 데이터렌더링 표준화
- 커스텀레시피와 정규레시피의 상세정보를 확인할 때 데이터가 서로 다르게 나열되는 문제점 해결.
=> Fix: 커스텀레시피와 정규레시피 세부정보 데이터렌더링 표준화

fe/src/components/myPage/MenuBar.tsx, fe/src/components/myPage/MyInfo.tsx, fe/src/pages/Mypage.tsx
-[ ] 기능 추가
-[ ] 기능 삭제
-[O] 코드 리팩토링
-[ ] 버그 수정
- Mypage 데이터 연결 변경
- Mypage edit 버튼 로직 수정
- MenuBar클릭시 색상변경 추가
- Mypage 기능 유지
- edit 버튼 클릭시 EditMyInfo 컴포넌트로 이동
- MenuBar클릭시 색상변경 추가
=> Refactor: Mypage 데이터 연결 및 타입, button 수정

fe/src/components/card/Card.tsx, fe/src/components/footer/Footer.tsx, fe/src/pages/Error.tsx, fe/src/pages/Main.tsx
-[ ] 기능 추가
-[ ] 기능 삭제
-[o] 코드 리팩토링
-[ ] 버그 수정
- 카드 description 표사 글자수 제한 취소
- 푸터 텍스트 변경
- 에러페이지 버튼 추가
에러 페이지에서 홈으로 이동 가능
=> Fix : 찜 목록 렌더링 오류

fe/src/components/card/Card.tsx
-[ ] 기능 추가
-[ ] 기능 삭제
-[o] 코드 리팩토링
-[ ] 버그 수정
=> Refactor : 카드 descriptoin 글자수 제한

fe/src/components/NavBar/NavBar.tsx
-[ ] 기능 추가
-[ ] 기능 삭제
-[O] 코드 리팩토링
-[ ] 버그 수정
- NavBar에서 밑줄이 2개가 생기는 오류 수정
- 다시 원래대로 1줄만 나오게 수정
=> Fix: NavBar 오류 수정

fe/src/components/card/Card.tsx
-[ ] 기능 추가
-[ ] 기능 삭제
-[o] 코드 리팩토링
-[ ] 버그 수정
- 가독성을 위해 text-align : end -> start 변경
- 가독성을 위해 자간, 행간 변경
- 레시피 카드의 hidden text가 왼쪽으로 정렬된다. 
- 자간과 행간이 넓어져 읽기 수월하다
=> Style : hidden text 정렬 end -> start, 행간/자간 변경

fe/src/components/header/Header.tsx, fe/src/components/myPage/MyRecipes.tsx, fe/src/hooks/useDeleteRecipe.ts, fe/src/hooks/useMainPagination.ts, fe/src/pages/SignIn.tsx, fe/src/pages/SignUp.tsx
-[ ] 기능 추가
-[ ] 기능 삭제
-[o] 코드 리팩토링
-[o] 버그 수정
- useDeleteRecipe hook 수정
- password input autocomplete : off 명시 
- header styled component prop 이름 변경: transient props
- 나의 레시피 삭제 가능
- 경고 메시지 제거
=> Fix: styled components prop 인식, 나의 레시피 삭제 불가, input 자동 완성 경고 메시지

fe/public/index.html
-[ ] 기능 추가
-[ ] 기능 삭제
-[ ] 코드 리팩토링
-[ ] 버그 수정
-[o] 의존성, 환경 변수, 빌드 관련 코드 업데이트
=> feat: upgrde-insecure mata 태그 추가
